### ISSUE TITLE
findprovs does't work for openSUSE Leap 42.1

### ISSUE THREAD

**Issue by matwey** [marguerite/golang-packaging#11]
Hello,

For instance, package golang-github-prometheus-client_golang doesn't provide anything on openSUSE Leap 42.1:

```
> rpm -q --provides -p golang-github-prometheus-client_golang-0.7.0+git20151127.67994f1-1.1.x86_64.rpm
предупреждение: golang-github-prometheus-client_golang-0.7.0+git20151127.67994f1-1.1.x86_64.rpm: Заголовок V3 DSA/SHA1 Signature, key ID 307d7bf9: NOKEY
golang-github-prometheus-client_golang = 0.7.0+git20151127.67994f1-1.1
golang-github-prometheus-client_golang(x86-64) = 0.7.0+git20151127.67994f1-1.1
```

```
> rpm -q --info -p golang-github-prometheus-client_golang-0.7.0+git20151127.67994f1-1.1.x86_64.rpm --
предупреждение: golang-github-prometheus-client_golang-0.7.0+git20151127.67994f1-1.1.x86_64.rpm: Заголовок V3 DSA/SHA1 Signature, key ID 307d7bf9: NOKEY
Name        : golang-github-prometheus-client_golang
Version     : 0.7.0+git20151127.67994f1
Release     : 1.1
Architecture: x86_64
Install Date: (not installed)
Group       : Development/Languages/Other
Size        : 13745009
License     : Apache-2.0
Signature   : DSA/SHA1, Вс 24 янв 2016 00:00:06, Key ID af4cfe4d307d7bf9
Source RPM  : golang-github-prometheus-client_golang-0.7.0+git20151127.67994f1-1.1.src.rpm
Build Date  : Сб 23 янв 2016 23:59:47
Build Host  : build75
Relocations : (not relocatable)
Vendor      : obs://build.opensuse.org/devel:languages:go
URL         : https://github.com/prometheus/client_golang
Summary     : Prometheus instrumentation library for Go applications
Description :
This is the Go client library for Prometheus.
Distribution: devel:languages:go / openSUSE_Leap_42.1
```

```
> rpm -q --list -p golang-github-prometheus-client_golang-0.7.0+git20151127.67994f1-1.1.x86_64.rpm --
предупреждение: golang-github-prometheus-client_golang-0.7.0+git20151127.67994f1-1.1.x86_64.rpm: Заголовок V3 DSA/SHA1 Signature, key ID 307d7bf9: NOKEY
/usr/bin/random
/usr/bin/simple
/usr/lib64/go/contrib/pkg/linux_amd64/github.com
/usr/lib64/go/contrib/pkg/linux_amd64/github.com/prometheus
/usr/lib64/go/contrib/pkg/linux_amd64/github.com/prometheus/client_golang
/usr/lib64/go/contrib/pkg/linux_amd64/github.com/prometheus/client_golang/api
/usr/lib64/go/contrib/pkg/linux_amd64/github.com/prometheus/client_golang/api/prometheus.a
/usr/lib64/go/contrib/pkg/linux_amd64/github.com/prometheus/client_golang/prometheus.a
/usr/share/doc/packages/golang-github-prometheus-client_golang
/usr/share/doc/packages/golang-github-prometheus-client_golang/LICENSE
/usr/share/doc/packages/golang-github-prometheus-client_golang/README.md
```

At the same time, the same package for openSUSE Factory provides the modules:

```
> rpm -q --provides -p golang-github-prometheus-client_golang-0.7.0+git20151127.67994f1-1.2.x86_64.rpm
предупреждение: golang-github-prometheus-client_golang-0.7.0+git20151127.67994f1-1.2.x86_64.rpm: Заголовок V3 DSA/SHA1 Signature, key ID 307d7bf9: NOKEY
golang(github.com/prometheus/client_golang)
golang(github.com/prometheus/client_golang/api/prometheus)
golang(github.com/prometheus/client_golang/prometheus)
golang-github-prometheus-client_golang = 0.7.0+git20151127.67994f1-1.2
golang-github-prometheus-client_golang(x86-64) = 0.7.0+git20151127.67994f1-1.2
```

**Comment by marguerite** [comment]
comparing those two pages:

[TW](https://build.opensuse.org/package/binary/devel:languages:go/golang-github-prometheus-client_golang?arch=x86_64&filename=golang-github-prometheus-client_golang-0.7.0%2Bgit20151127.67994f1-1.1.x86_64.rpm&repository=openSUSE_Tumbleweed)

[Leap](https://build.opensuse.org/package/binary/devel:languages:go/golang-github-prometheus-client_golang?arch=x86_64&filename=golang-github-prometheus-client_golang-0.7.0%2Bgit20151127.67994f1-1.1.x86_64.rpm&repository=openSUSE_Leap_42.1)

It looks to me that the golang.prov and golang.req were never called by RPM at all on Leap.

**Comment by marguerite** [comment]
that is, 

<pre>
%go_provides \
%if 0%{?suse_version} < 1320 \
%global _use_internal_dependency_generator 0 \
%global __find_provides %{_prefix}/lib/rpm/golang.prov \
%global __find_requires %{_prefix}/lib/rpm/golang.req \
%endif \
%go_exclusivearch \
Provides:       %{name}-devel = %{version} \
Provides:       %{name}-devel-static = %{version}
</pre>

in macros.go didn't work ( Leap's suse_version is 1315).

**Comment by marguerite** [comment]
I tweaked the golang-packaging to output the arguments RPM passed through to it:

TW:

<pre>
[   78s] Provides: /home/abuild/rpmbuild/BUILDROOT/golang-github-prometheus-client_golang-0.7.0+git20151127.67994f1-3.2.i386/usr/bin/random\n /home/abuild/rpmbuild/BUILDROOT/golang-github-prometheus-client_golang-0.7.0+git20151127.67994f1-3.2.i386/usr/bin/simple\n /home/abuild/rpmbuild/BUILDROOT/golang-github-prometheus-client_golang-0.7.0+git20151127.67994f1-3.2.i386/usr/lib/go/contrib/pkg/linux_386/github.com/prometheus/client_golang/api/prometheus.a\n /home/abuild/rpmbuild/BUILDROOT/golang-github-prometheus-client_golang-0.7.0+git20151127.67994f1-3.2.i386/usr/lib/go/contrib/pkg/linux_386/github.com/prometheus/client_golang/prometheus.a\n 
</pre>

Leap:

<pre>
[   96s] Provides: golang-github-prometheus-client_golang = 0.7.0+git20151127.67994f1-3.1 golang-github-prometheus-client_golang(x86-64) = 0.7.0+git20151127.67994f1-3.1
</pre>

The result on Leap would had been all the files from buildroot (because there's no fileattr filter)

so the macros were never called.

**Comment by marguerite** [comment]
you have no %go_provides macro in specfile, which is standard. invalid issue
