### ISSUE TITLE
Fails to build on Power

### ISSUE THREAD

**Issue by k0da** [marguerite/golang-packaging#12]
[   28s] /home/abuild/rpmbuild/BUILD/golang-packaging-14.5/golang/rpmsysinfo.rb:83:in `get_go_contribdir': uninitialized class variable @@libdir in RpmSysinfo (NameError)
[   28s]    from /home/abuild/rpmbuild/BUILD/golang-packaging-14.5/golang/filelists.rb:9:in`&lt;module:Filelists&gt;'
[   28s]    from /home/abuild/rpmbuild/BUILD/golang-packaging-14.5/golang/filelists.rb:1:in `&lt;top (required)&gt;'
[   28s]    from /usr/lib64/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
[   28s]    from /usr/lib64/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
[   28s]    from ./golang-macros.rb:8:in`&lt;main&gt;'
[   28s] + GOARCH=
[   28s] error: Bad exit status from /var/tmp/rpm-tmp.YnysZH (%prep)

**Comment by marguerite** [comment]
will release a package tomorrow
