### ISSUE TITLE
Requires could be extracted directly from .a files

### ISSUE THREAD

**Issue by matwey** [marguerite/golang-packaging#3]
Look at `.a` files, they can be extracted using `ar x file.a`.
In each archive `file.a` there is a text file `__.PKGDEF` containing (among other) list of imports:

```
        import gollectd "github.com/kimor79/gollectd"
```

This is the more direct way which does not rely on scanning sources on build system, you only need to scan the files which are provided to prov.find by RPM on standard input.

**Comment by marguerite** [comment]
Thanks for the hint! That's brilliant!

where's `prov.find` then? or I have to get them like what I did in golang.prov?

Marguerite

**Comment by matwey** [comment]
Oh, sorry, I mean `golang.req`.

**Comment by marguerite** [comment]
okay! I'm implementing it!

**Comment by marguerite** [comment]
@matwey 

Hi, what if the `.so` files? 

golang 1.5 supports shared linking, can you please see if there's any way to get `imports` from them? I didn't find any project that can be built successfully with `-buildmode=shared -linkshared`, maybe you can write one for me to test?

**Comment by marguerite** [comment]
@matwey 

the new `golang.req` works well.

https://build.opensuse.org/package/binary/home:MargueriteSu:branches:devel:languages:go/golang-googlecode-log4go?arch=i586&filename=golang-googlecode-log4go-3.0.1+git20151210.8e9057c-8.2.i586.rpm&repository=openSUSE_Tumbleweed

but we need to run the same script on `go` main package itself which provides system modules.

**Comment by marguerite** [comment]
release v13 implemented that. save .so files for future research. issue closed.
