### ISSUE TITLE
-tags support is required for build macro

### ISSUE THREAD

**Issue by matwey** [marguerite/golang-packaging#7]
Sometimes custom tag has to be specified on build/install.

See for example `-tag popcntgo`:
https://github.com/dgryski/go-bits/commit/dffe1d50093678b150156c4ad97029473994f459

**Comment by marguerite** [comment]
Ok. Thanks for notice.

**Comment by marguerite** [comment]
@matwey 

it has been implemented. you can branch go and golang-packaging from home:MargueriteSu:branches:devel:languages:go to test this feature with "%gobuild -tags 'popcntgo' ..."

I just have no time...I'm busy fixing [issue#6](https://github.com/marguerite/golang-packaging/issues/6)

**Comment by marguerite** [comment]
@matwey 

fixed in master, see: https://build.opensuse.org/package/show/home:MargueriteSu:branches:devel:languages:go/golang-github-dgryski-go-bits

`%gobuild -tags "popcntgo" ...`
