### ISSUE TITLE
$GOPATH not set correctly

### ISSUE THREAD

**Issue by grb43** [marguerite/golang-packaging#8]
I have been building my own syncthing packages for openSUSE 13.1 because syncthing requires go 1.3+ which is not available in the original distro. So on the advice of a syncthing maintainer I established a project, linked it to go & go1.4 in the devel:languages:go project and was able to produce my own syncthing packages.

Following go revision 242, when golang-macros.rb was added, syncthing would no longer compile. A series of errors were logged stating that various library packages could not be found. I suspect this is due to $GOPATH being set incorrectly.

A sample of the error log is shown below:

<code>GOPATH=/home/abuild/rpmbuild/BUILD/syncthing/Godeps/_workspace:/home/abuild/go:/usr/share/go/contrib

cmd/stcompdirs/main.go:19:2: cannot find package "github.com/syncthing/syncthing/lib/symlinks" in any of:
- /usr/lib64/go/src/github.com/syncthing/syncthing/lib/symlinks (from $GOROOT)  
- home/abuild/rpmbuild/BUILD/syncthing/Godeps/_workspace/src/github.com/syncthing/syncthing/lib/symlinks (from $GOPATH)  
- /home/abuild/go/src/github.com/syncthing/syncthing/lib/symlinks  
- /usr/share/go/contrib/src/github.com/syncthing/syncthing/lib/symlinks</code>

The actual path to the library packages is:

 /home/abuild/rpmbuild/BUILD/go/src/github.com/syncthing/syncthing/lib/symlinks

Reverting to go version 241 has fixed the problem for the moment and $GOPATH is now logged as

<code>GOPATH=/home/abuild/rpmbuild/BUILD/syncthing/Godeps/_workspace:/home/abuild/rpmbuild/BUILD/go</code>

**Comment by marguerite** [comment]
@grb43 

seems you used custom builds. 

the old `prep` macro is written in bash. if it sets some environment variables, they'll leave there. so your $BUILDFLAGS works.

but the new  `prep` macro is written in ruby. ruby can't set system environment variables for its parent process (I mean the shell that runs it).

so either you need to make it "fully customed" or adapt to the new macros, which means let %gobuild handle the build.

I just branched the package. I'll see if I can port it to the new method.

**Comment by marguerite** [comment]
Actually the current method you use to build syncthing is wrong...

https://build.opensuse.org/build/home:grb01/openSUSE_13.1/x86_64/syncthing/_log

see those errors of missing dependencies. or see my version:

https://build.opensuse.org/package/live_build_log/home:MargueriteSu:branches:devel:languages:go/syncthing/openSUSE_Tumbleweed/x86_64

the go build method will get you a binary (which suppressed the errors) , but actually it's not functional. 

you need a few dependencies packaged first.

**Comment by grb43** [comment]
Thanks for your replies.

As I said originally, I am a novice at this and don't know how to 
correct these "errors". I simply branched network:syncthing which, I 
understand, provides the development package for factory.

I  notice neither network:syncthing nor openSUSE:factory:syncthing are 
now building against the latest go 1.5.2 so, hopefully, the 
network:syncthing mainainers will sort it out. I will send them a copy 
of your email if I can find a way to do so.

Again, many thanks

Graeme

**Comment by marguerite** [comment]
BuildRequires:  golang(github.com/bkaradzic/go-lz4)
BuildRequires:  golang(github.com/calmh/du)
BuildRequires:  golang(github.com/calmh/luhn)
BuildRequires:  golang(github.com/calmh/xdr)
BuildRequires:  golang(github.com/juju/ratelimit)
BuildRequires:  golang(github.com/kardianos/osext)
BuildRequires:  golang(github.com/rcrowley/go-metrics)
BuildRequires:  golang(github.com/stathat/go)
BuildRequires:  golang(github.com/syndtr/goleveldb)
BuildRequires:   golang(github.com/golang/snappy)
BuildRequires:   golang(github.com/onsi/ginkgo)
BuildRequires:   golang(github.com/onsi/gomega)
BuildRequires:  golang(github.com/thejerf/suture)
BuildRequires:  golang(github.com/vitrun/qart)
BuildRequires:  golang(golang.org/x/crypto)
BuildRequires:  golang(golang.org/x/net)
BuildRequires:  golang(golang.org/x/text)

it needs these BuildRequires

**Comment by marguerite** [comment]
network:syncthing looks like devel project for openSUSE to me, too. but apparently they're maintaining a broken package.

Back to your original issue, it happens because %goprep now don't set environment variable "GOPATH" for the whole build. 

<pre>
GOPATH=/home/abuild/rpmbuild/BUILD/syncthing/Godeps/_workspace:/home/abuild/go:/usr/share/go/contrib
</pre>

is the default go path for system.

<pre>
/home/abuild/rpmbuild/BUILD/go
</pre>

was the one added by GOPATH env.

so if you want to restore to the past behavior, just add 

`export GOPATH=%{_builddir}/go` will work.

but anyway the build is broken.

What I need to fix is the package, not the packaging tool.

**Comment by grb43** [comment]
I understand, makes sense even to me. So thank you.

For the moment, I have hacked the spec file to manually export GOPATH 
and everything compiles again.

Not sure what the next step is to fix the real problem. I will forward 
your latest comments to the Syncthing maintainer and see if there is any 
response.

Graeme

**Comment by marguerite** [comment]
actually I have fixed it. 

see: 

https://build.opensuse.org/package/show/home:MargueriteSu:branches:devel:languages:go/syncthing

I just found a minor problem with my Provides generation script. 

syncthing builds well with my method. I'll commit to network:syncthing when I finished fixing issues from golang-packaging side.

**Comment by marguerite** [comment]
you can consider it as fixed. 

https://build.opensuse.org/request/show/353066

**Comment by grb43** [comment]
Good news, thanks for that.
